# Generated by Django 5.0.6 on 2024-07-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskLabelRelation',
            new_name='TaskLabel',
        ),
    ]
